### ISSUE TITLE
[1.0.1] Responsive styles removed

### ISSUE THREAD

**Issue by peterchrjoergensen** [optimistdigital/nova-tailwind#1]
When you disabled flex, flexDirection, flexGrow and others in the tailwind.config.js file, the responsive styles were removed as well, which I was using for a card.

[Changelog](https://github.com/optimistdigital/nova-tailwind/compare/1.0.0...1.0.1#diff-8927db3d5d9a070423893c3ca4c68042R76-R91)

Not sure if it it's a bug, but I thought to mention it anyway. Maybe there's a middle ground? Only responsive styles enabled?

Thanks for the package!

**Comment by Tarpsvo** [comment]
Hi! Sorry for the delay, I was on vacation.

Can you specify which classes stopped working? Nova has already included `flexbox: ['responsive']` variant, so I assumed all the responsive flex related classes are already there.

**Comment by Tarpsvo** [comment]
Hey again! I added back flex and its subsidiaries. All the responsive styles should be back now. Check out 1.0.2.

**Comment by peterchrjoergensen** [comment]
In my case, it was specifically the flexGrow classes, but I see you figured it out.

Thanks for the release! 👍
