### ISSUE TITLE
No Fields on Detail View

### ISSUE THREAD

**Issue by mstaack** [optimistdigital/nova-tailwind#10]
For some weird reason  i am missing some detail fields (uses spatie/translatable and nova-tiptap)

using: https://github.com/manogi/nova-tiptap & https://github.com/spatie/laravel-translatable & https://github.com/optimistdigital/nova-translatable

downgrading fixes this:
```
Package operations: 0 installs, 1 update, 1 removal
  - Removing optimistdigital/nova-tailwind (1.1.3)
  - Downgrading manogi/nova-tiptap (v2.0.0 => v1.4.1): Extracting archive
 ```

i assume its related to nova-tailwind? do you have any ideas?

missing fields on detail view:
![image](https://user-images.githubusercontent.com/10169509/149118853-6addcd62-6b51-4cce-9156-dd6c0fb77c6c.png)

edit mode works:
![image](https://user-images.githubusercontent.com/10169509/149118930-ab0e0beb-23ae-4e28-8200-2652d82df2e1.png)

**Comment by mstaack** [comment]
ok its getting even weirder, i am not able to solve this really by downgrading. somehow it feels like a js race condition or so?

**Comment by Tarpsvo** [comment]
It's because nova-tiptap-field doesn't render anything on the detail field. Nothing to do with tailwind or translatable packages.

https://github.com/manogi/nova-tiptap/blob/master/resources/js/components/DetailField.vue

**Comment by Tarpsvo** [comment]
Nova TipTap V1 does have a proper DetailField component.

https://github.com/manogi/nova-tiptap/blob/tiptap-v1/resources/js/components/DetailField.vue

**Comment by mstaack** [comment]
oh man, thank you very much for the explanation!
