### ISSUE TITLE
[Feature Request] Tailwind CSS v2.0+

### ISSUE THREAD

**Issue by eugenevdm** [optimistdigital/nova-tailwind#3]
I just looked in my up to date Laravel Nova 3.20.

From the `package.json` file is appears Laravel Nova's Tailwind is really out of date:

`"tailwindcss": "^0.6.0",`

Not sure if this could be correct, and then if the purpose of this project was to bring Tailwind up to a newer version. For what it's worth, I'm dying to use Tailwind 2.0+ classes in my Laravel Nova application.

**Comment by Tarpsvo** [comment]
Hi! Tailwind 2.0 is now released in version 1.1.0. Good luck! :)
