### ISSUE TITLE
Colors are missing

### ISSUE THREAD

**Issue by iamoat** [optimistdigital/nova-tailwind#5]
With tailwind 2.x some default colors are missing. They are moved to 'tailwindcss/colors'. 

For example, teal is not available in the default colors anymore. 

We apparently need to do a 'require('tailwindcss/colors')' in order to use it. 

I don't know where to put this it. 

// tailwind.config.js
const colors = require('tailwindcss/colors')

![image](https://user-images.githubusercontent.com/1286835/106407460-b2919e80-646e-11eb-8540-428c95ed3a1f.png)

**Comment by Tarpsvo** [comment]
Hmm, it seems that Tailwind 2.X doesn't have `teal` anymore. They've changed their colour arrangement a bit. The colors defined in the documentation are included (ie pink-200, green-600...).

See: https://tailwindcss.com/docs/customizing-colors

**Comment by iamoat** [comment]
I submitted a PR for this. Please check and merge.

**Comment by Tarpsvo** [comment]
Hi! Thanks for the PR. :) I merged it and released it in version 1.1.3.
