### ISSUE TITLE
w-1/2 missing?

### ISSUE THREAD

**Issue by gizburdt** [optimistdigital/nova-tailwind#7]
I would like to use w-1/2 and md:w-1/2, but I think they're missing. Can they be added or am I missing something?

**Comment by Tarpsvo** [comment]
Hi!  `w-1/2` is provided by Laravel Nova. It seems to work for me. However, the md part is not provided by Nova I think. I'll add it to this package.

**Comment by Tarpsvo** [comment]
Added now in version 1.1.2.
