### ISSUE TITLE
how to use this package inside blade?

### ISSUE THREAD

**Issue by Pamposgsk** [optimistdigital/nova-tailwind#8]
Hi,
Iam using laravel nova and i want to run an action to export resource  table in pdf.
currently iam using blade templates for the pdfs.How can i use tailwind css inside a blade file?
Thanks

**Comment by Tarpsvo** [comment]
Heya! Currently, it's fairly difficult to use inside a PDF. I would have to add a function that exports the CSS to your resources or public folder. But even then there's a downside to using this - the CSS, unzipped, is 2.9MB and I don't think it's a smart idea to include this in your PDF file. I would personally just write CSS for a PDF explicitly.
